version: '3.2'

services: 
  iex_database:
    image: "postgres:13"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - iex_data_database:/var/lib/postgresql/data  
    restart: always
   
volumes:
  iex_data_database: